//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxCsPlayground.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RxCsPlayground.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ábelová
        ///Abovce
        ///Abrahám
        ///Abrahámovce / okres Bardejov
        ///Abrahámovce / okres kezmarok
        ///Abramová
        ///Abranovce
        ///Adamovské Kochanovce
        ///Adidovce
        ///Alekšince
        ///Andovce
        ///Andrejová
        ///Ardanovce
        ///Ardovo
        ///Arnutovce
        ///Báb
        ///Babie
        ///Babín
        ///Babiná
        ///Babindol
        ///Babinec
        ///Bacúch
        ///Bacúrov
        ///Báč
        ///Bačka
        ///Bačkov
        ///Bačkovík
        ///Baďan
        ///Bádice
        ///Badín
        ///Báhoň
        ///Bajany
        ///Bajč
        ///Bajerov
        ///Bajerovce
        ///Bajka
        ///Bajtava
        ///Baka
        ///Baláže
        ///Baldovce
        ///Balog nad Ipľom
        ///Baloň
        ///Baňa
        ///Banka
        ///Bánov
        ///Bánovce nad Bebravou
        ///Bánovce nad Ondavou
        ///Banská Belá
        ///Banská Bystrica        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CitiesList {
            get {
                return ResourceManager.GetString("CitiesList", resourceCulture);
            }
        }
    }
}
